import { describe, expect, it } from "vitest";
import {
  buildReport,
  formatConvergenceMessage,
  renderReportMarkdown,
} from "../src/report";
import { initLoopState } from "../src/loop";
import type { IterationScores, LoopConfig } from "../src/types";
import { DEFAULTS } from "../src/types";

const config: LoopConfig = { ...DEFAULTS, maxIterations: 5 };

function makeBaseline(): IterationScores {
  return {
    iteration: 0,
    timestamp: "2026-03-25T00:00:00.000Z",
    scores: { lint: 70, tests: 80 },
    compositeScore: 75,
    delta: 0,
    tokensUsed: 0,
    durationMs: 0,
    status: "improved",
  };
}

describe("buildReport", () => {
  it("should calculate improvement percentages", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    state.iterations.push({
      iteration: 1,
      timestamp: "2026-03-25T00:01:00.000Z",
      scores: { lint: 90, tests: 95 },
      compositeScore: 92,
      delta: 17,
      tokensUsed: 1000,
      durationMs: 500,
      status: "improved",
    });
    state.currentIteration = 1;
    state.stopReason = "converged";

    const report = buildReport(state);
    expect(report.improvement.lint).toBeCloseTo(28.57, 1); // (90-70)/70 * 100
    expect(report.improvement.tests).toBeCloseTo(18.75, 1); // (95-80)/80 * 100
    expect(report.compositeImprovement).toBeGreaterThan(0);
  });

  it("should handle zero baseline gracefully", () => {
    const baseline = makeBaseline();
    baseline.scores = { lint: 0, tests: 80 };
    baseline.compositeScore = 40;
    const state = initLoopState(config, ["src/"], baseline, "test");
    state.iterations.push({
      iteration: 1,
      timestamp: "2026-03-25T00:01:00.000Z",
      scores: { lint: 50, tests: 90 },
      compositeScore: 70,
      delta: 30,
      tokensUsed: 500,
      durationMs: 200,
      status: "improved",
    });
    state.currentIteration = 1;

    const report = buildReport(state);
    expect(report.improvement.lint).toBe(100); // 0→50 = 100% improvement
  });

  it("should include learning report when provided", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    const report = buildReport(state, "This code improved because...");
    expect(report.learningReport).toBe("This code improved because...");
  });
});

describe("renderReportMarkdown", () => {
  it("should produce valid markdown with all sections", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    state.iterations.push({
      iteration: 1,
      timestamp: "2026-03-25T00:01:00.000Z",
      scores: { lint: 85, tests: 90 },
      compositeScore: 87,
      delta: 12,
      tokensUsed: 1000,
      durationMs: 500,
      status: "improved",
    });
    state.currentIteration = 1;
    state.stopReason = "max_iterations";

    const report = buildReport(state);
    const md = renderReportMarkdown(report);

    expect(md).toContain("# Autoresearch Report:");
    expect(md).toContain("## Improvement Summary");
    expect(md).toContain("## Iteration History");
    expect(md).toContain("Generated by /autoresearch");
  });

  it("should include convergence analysis when converged", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    state.iterations.push({
      iteration: 1,
      timestamp: "2026-03-25T00:01:00.000Z",
      scores: { lint: 85 },
      compositeScore: 85,
      delta: 0.3,
      tokensUsed: 500,
      durationMs: 200,
      status: "improved",
    });
    state.currentIteration = 1;
    state.stopReason = "converged";

    const report = buildReport(state);
    const md = renderReportMarkdown(report);
    expect(md).toContain("## Convergence Analysis");
  });

  it("should include scope proposals when present", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    state.scopeExpansionProposals.push({
      file: "config.ts",
      description: "Could improve error handling",
      estimatedImpact: "medium",
      relatedConstraints: ["lint"],
    });
    state.currentIteration = 0;

    const report = buildReport(state);
    const md = renderReportMarkdown(report);
    expect(md).toContain("Out-of-Scope Improvement Proposals");
    expect(md).toContain("config.ts");
  });
});

describe("formatConvergenceMessage", () => {
  it("should include key convergence information", () => {
    const state = initLoopState(config, ["src/"], makeBaseline(), "test");
    state.iterations.push(
      { iteration: 1, timestamp: "", scores: {}, compositeScore: 76, delta: 1, tokensUsed: 500, durationMs: 200, status: "improved" },
      { iteration: 2, timestamp: "", scores: {}, compositeScore: 76.3, delta: 0.3, tokensUsed: 500, durationMs: 200, status: "improved" },
      { iteration: 3, timestamp: "", scores: {}, compositeScore: 76.4, delta: 0.1, tokensUsed: 500, durationMs: 200, status: "improved" },
    );
    state.currentIteration = 3;

    const msg = formatConvergenceMessage(state);
    expect(msg).toContain("diminishing returns");
    expect(msg).toContain("/autoresearch --resume");
  });
});
