// Satisfies: U1 (Live Progress + Report), B3 (Measurable Improvement), TN7 (Learning Summary)
// Satisfies: U3 (Convergence Communication)
// Summary report generator — produces the final markdown report

import { computeImprovementPct, lastIteration } from "./shared";
import type { AutoresearchReport, IterationScores, LoopState } from "./types";

/** Build the final report from loop state. Satisfies: B3, U1, TN7 */
export function buildReport(
  state: LoopState,
  learningReport?: string
): AutoresearchReport {
  const improvement: Record<string, number> = {};
  const latest = lastIteration(state);
  const finalScores = latest?.scores ?? state.baseline.scores;

  for (const [id, baselineScore] of Object.entries(state.baseline.scores)) {
    const finalScore = finalScores[id] ?? baselineScore;
    improvement[id] = computeImprovementPct(baselineScore, finalScore);
  }

  const baselineComposite = state.baseline.compositeScore;
  const finalComposite = latest?.compositeScore ?? baselineComposite;
  const compositeImprovement = computeImprovementPct(baselineComposite, finalComposite);

  return {
    runId: state.runId,
    scope: state.scope,
    startedAt: state.startedAt,
    completedAt: new Date().toISOString(),
    totalIterations: state.currentIteration,
    stopReason: state.stopReason ?? "unknown",
    baseline: state.baseline.scores,
    final: finalScores,
    improvement,
    compositeImprovement,
    iterationHistory: state.iterations,
    scopeProposals: state.scopeExpansionProposals,
    learningReport,
  };
}

/** Render the metadata header section */
function renderMetadata(report: AutoresearchReport): string[] {
  const sign = report.compositeImprovement >= 0 ? "+" : "";
  return [
    `# Autoresearch Report: ${report.runId}`,
    "",
    "| Field | Value |",
    "|-------|-------|",
    `| **Scope** | ${report.scope.join(", ")} |`,
    `| **Started** | ${report.startedAt} |`,
    `| **Completed** | ${report.completedAt} |`,
    `| **Iterations** | ${report.totalIterations} |`,
    `| **Stop Reason** | ${report.stopReason} |`,
    `| **Composite Improvement** | ${sign}${report.compositeImprovement.toFixed(1)}% |`,
    "",
  ];
}

/** Render the per-constraint improvement table */
function renderImprovementTable(report: AutoresearchReport): string[] {
  const lines = [
    "## Improvement Summary",
    "",
    "| Constraint | Baseline | Final | Change |",
    "|------------|----------|-------|--------|",
  ];
  for (const [id, pct] of Object.entries(report.improvement)) {
    const baseline = report.baseline[id] ?? 0;
    const final = report.final[id] ?? 0;
    const sign = pct >= 0 ? "+" : "";
    lines.push(`| ${id} | ${baseline} | ${final} | ${sign}${pct.toFixed(1)}% |`);
  }
  lines.push("");
  return lines;
}

/** Render the iteration history table */
function renderIterationHistory(report: AutoresearchReport): string[] {
  const lines = [
    "## Iteration History",
    "",
    "| # | Score | Delta | Status | Tokens | Duration |",
    "|---|-------|-------|--------|--------|----------|",
  ];
  for (const iter of report.iterationHistory) {
    const delta = iter.delta >= 0 ? `+${iter.delta.toFixed(1)}` : iter.delta.toFixed(1);
    lines.push(
      `| ${iter.iteration} | ${iter.compositeScore} | ${delta} | ${iter.status} | ${iter.tokensUsed} | ${(iter.durationMs / 1000).toFixed(1)}s |`
    );
  }
  lines.push("");
  return lines;
}

/** Render report as markdown. Satisfies: U1, B3 */
export function renderReportMarkdown(report: AutoresearchReport): string {
  const lines: string[] = [
    ...renderMetadata(report),
    ...renderImprovementTable(report),
    ...renderIterationHistory(report),
  ];

  // Convergence trend. Satisfies: U3
  if (report.stopReason === "converged") {
    lines.push("## Convergence Analysis", "");
    lines.push("The loop stopped due to diminishing returns. Last iterations:", "");
    for (const iter of report.iterationHistory.slice(-5)) {
      const bar = "\u2588".repeat(Math.max(0, Math.round(iter.delta)));
      lines.push(`  Iteration ${iter.iteration}: delta=${iter.delta.toFixed(2)} ${bar}`);
    }
    lines.push("", "> To resume from this point, run `/autoresearch --resume`", "");
  }

  // Scope expansion proposals. Satisfies: TN3
  if (report.scopeProposals.length > 0) {
    lines.push("## Out-of-Scope Improvement Proposals", "");
    lines.push("The following improvements were identified but require files outside the current scope:", "");
    for (const p of report.scopeProposals) {
      lines.push(`### ${p.file} (${p.estimatedImpact} impact)`, "", p.description);
      lines.push(`Related constraints: ${p.relatedConstraints.join(", ")}`, "");
    }
  }

  // Learning report. Satisfies: TN7
  if (report.learningReport) {
    lines.push("## Learning Report", "");
    lines.push("Full LLM evaluation of all changes with explanations:", "");
    lines.push(report.learningReport, "");
  }

  lines.push("---", "*Generated by /autoresearch*");
  return lines.join("\n");
}

/** Format convergence communication for auto-stop display. Satisfies: U3 */
export function formatConvergenceMessage(state: LoopState): string {
  const plateauSlice = state.iterations.slice(-state.config.plateauWindow);
  const deltas = plateauSlice.map((i) => i.delta.toFixed(2)).join(", ");
  const latest = lastIteration(state) as IterationScores | undefined;
  const totalImprovement = latest
    ? latest.compositeScore - state.baseline.compositeScore
    : 0;

  return `
Autoresearch loop auto-stopped: diminishing returns detected.

Last ${state.config.plateauWindow} iteration deltas: [${deltas}]
Threshold: ${state.config.convergenceThreshold}
Total improvement: ${totalImprovement >= 0 ? "+" : ""}${totalImprovement.toFixed(1)} points (${state.baseline.compositeScore} → ${latest?.compositeScore ?? state.baseline.compositeScore})
Iterations completed: ${state.currentIteration}/${state.config.maxIterations}

To resume: /autoresearch --resume
To view full report: see .autoresearch/report.md
`.trim();
}
